# Generated by Django 4.1.3 on 2023-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0003_remove_ativo_id_ativo_id_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativo",
            name="id_usuario",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
