# Generated by Django 4.1.3 on 2023-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativo",
            name="nome",
            field=models.TextField(max_length=255),
        ),
    ]
