# Generated by Django 4.1.3 on 2023-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0005_rename_id_usuario_ativo_id_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="datas",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ativo",
            name="limite_inferior",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ativo",
            name="limite_superior",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
