# Generated by Django 4.1.3 on 2023-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0002_alter_ativo_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativo",
            name="id",
        ),
        migrations.AddField(
            model_name="ativo",
            name="id_usuario",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
