# Generated by Django 4.1.3 on 2023-08-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0004_alter_ativo_id_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ativo",
            old_name="id_usuario",
            new_name="id_ativo",
        ),
    ]
