# Generated by Django 4.1.3 on 2023-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_INOA", "0006_ativo_datas_ativo_limite_inferior_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="delay",
            field=models.IntegerField(default=1000),
        ),
    ]
